name: build-apk
on: { workflow_dispatch: {}, push: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3
      - name: install android sdks
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # use the repo's wrapper to avoid version drift
      - name: gradle info
        run: ./gradlew --version

      - name: build debug apk (with full logs)
        run: |
          ./gradlew --no-daemon clean assembleDebug --stacktrace --info | tee build.log

      - name: list outputs
        if: always()
        run: |
          ls -R app/build/outputs || true
          find . -name "*.apk" -type f -print || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug
          path: |
            app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/**/*.apk
            build.log
